#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/neodesk/neodesk /usr/bin/neodesk

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/neodesk.service ]; then
			rm /etc/systemd/system/neodesk.service /usr/lib/systemd/system/neodesk.service /usr/lib/systemd/user/neodesk.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/neodesk/files/systemd/neodesk.service /usr/lib/systemd/system/neodesk.service
		# try fix error in Ubuntu 18.04
		# Failed to reload neodesk.service: Unit neodesk.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/neodesk.service:10: Executable path is not absolute: pkill -f "neodesk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/neodesk.service
		fi
		systemctl daemon-reload
		systemctl enable neodesk
		systemctl start neodesk
	fi
fi
